# Name of your site (displayed in the header)
name: Gianni Tedesco
author: Gianni Tedesco
title: scaramanga
email: your-email@example.com
description: The hacker with the supernumerary nipple
url: https://giannitedesco.github.io
#baseurl: "" # the subpath of your site, e.g. /blog
disqus:
github_username:  giannitedesco
google_analytics: UA-158175838-1
show_excerpts: true

# Build settings
theme: jekyll-theme-hacker
markdown: kramdown
plugins:
  - jekyll-feed
